### ISSUE TITLE
Hardcoded policy's to attach have incorrect paths

### ISSUE THREAD

**Issue by ptravishill** [clowdhaus/terraform-aws-managed-service-grafana#5]
## Description

Error: Error attaching policy arn:aws:iam::aws:policy/AmazonGrafanaAthenaAccess to IAM Role. NoSuchEntity: Policy arn:aws:iam::aws:policy/AmazonGrafanaAthenaAccess does not exist or is not attachable. status code: 404

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]:
- `v1.3.0`
- Terraform version:
`v1.1.7`
- Provider version(s):
`hashicorp/aws v4.18.0`

## Reproduction Code [Required]

```
module "managed_grafana" {
  source  = "terraform-aws-modules/managed-service-grafana/aws"
  version = "v1.3.0"

  # Workspace
  name                     = "grafana-${local.cluster_name}"
  associate_license        = false
  description              = "AWS Managed Grafana for ${local.cluster_name}"
  account_access_type      = "CURRENT_ACCOUNT"
  authentication_providers = ["SAML"]
  permission_type          = "SERVICE_MANAGED"
  data_sources = [
    "AMAZON_OPENSEARCH_SERVICE",
    "ATHENA",
    "CLOUDWATCH",
    "PROMETHEUS",
    "REDSHIFT",
    "SITEWISE",
    "TIMESTREAM",
    "XRAY"
  ]
  notification_destinations = ["SNS"]
  stack_set_name            = "grafana-${local.cluster_name}"

  # Workspace IAM role
  create_iam_role                = true
  iam_role_name                  = "${local.cluster_name}-managed-grafana-role"
  use_iam_role_name_prefix       = false
  iam_role_description           = "IAM Role for AWS Managed Grafana"
  iam_role_path                  = "/grafana/"
  iam_role_force_detach_policies = true
  iam_role_max_session_duration  = 7200

  # Workspace SAML configuration
  saml_admin_role_values  = ["DevOps"]
  saml_editor_role_values = ["editor"]
  saml_email_assertion    = "mail"
  saml_groups_assertion   = "groups"
  saml_login_assertion    = "mail"
  saml_name_assertion     = "displayName"
  saml_org_assertion      = "org"
  saml_role_assertion     = "DevOps"
  saml_idp_metadata_xml   = file("${path.module}/idp/dev.xml")
}
```

## Expected behavior

Apply without error

## Actual behavior

Error on apply

## Additional context

It seems that [Redshift](https://github.com/terraform-aws-modules/terraform-aws-managed-service-grafana/blob/master/main.tf#L223) and [Athena](https://github.com/terraform-aws-modules/terraform-aws-managed-service-grafana/blob/master/main.tf#L227) have incorrect policy paths hardcoded. 

It should be:
`arn:aws:iam::aws:policy/service-role/AmazonGrafanaAthenaAccess` and `arn:aws:iam::aws:policy/service-role/AmazonGrafanaRedshiftAccess`

**Comment by antonbabenko** [comment]
This issue has been resolved in version 1.3.1 :tada:
